# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9bd42c72f3e6ddc173e41850ad301e7868c2310a91c49e4c69d8772010dba8308d105cd9f3a81b8da2b87c7e210b5ff73b4c3241bd4c02c04310886e5e812aa

test:
  secret_key_base: 1a80057e9a015e1bf6b68c220c689f8981fefaef1534a6233d3ff4d3a0f20684af0d6160f14c9d2ad99bc78ad438618e4fe93ebcfcc03f1ef6eafa1714273853

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
